### ISSUE TITLE
Serving JS Files not Working

### ISSUE THREAD

**Issue by AlexanderElias** [iron/staticfile#49] opened 2015-07-25 00:38 UTC
Serving JS Files not Working on a Clean linux Server But works Locally on Mac. 

I thought I was going crazy at first but there is definitely an issue. Or I missed something really foolish. 

I spun up a vps on digitalocean installed rust, dependencies, and tested. Then I pull in the site code from my git repo. After cargo run and visiting my address and port the javascript  files just keep pending. But the really weird part is that the same code works fine locally on my mac. I also found another issue which I was planning on contributing to in Iron. 

<img width="1415" alt="screen shot 2015-07-24 at 5 33 41 pm" src="https://cloud.githubusercontent.com/assets/6393261/8887085/3d3be9c8-322a-11e5-95c1-1b95264bff72.png">

<img width="1424" alt="screen shot 2015-07-24 at 5 33 03 pm" src="https://cloud.githubusercontent.com/assets/6393261/8887073/1814f04a-322a-11e5-8d54-ad848a16f5a9.png">

**Comment by reem** [comment] 2015-07-25 03:42
@AlexanderElias can you include code to reproduce or at least the full headers of the request and responses for the js files? Also, what do you mean by "not working"?

**Comment by AlexanderElias** [comment] 2015-07-27 15:50
Sorry it took me so long to respond I had a project I was trying to get finished up.

Yeah, here is a link to my project: <a href="https://github.com/AlexanderElias/cs-iron">https://github.com/AlexanderElias/cs-iron</a>
* Main.rs: <a href="https://github.com/AlexanderElias/cs-iron/blob/master/src/main.rs">https://github.com/AlexanderElias/cs-iron/blob/master/src/main.rs</a>
* Header.html: <a href="https://github.com/AlexanderElias/cs-iron/blob/master/views/header.html">https://github.com/AlexanderElias/cs-iron/blob/master/views/header.html</a>

Oh yes certainly, the part that is not working is that the JS files are not loading. The image I attached shows that the Javascript files just continue to pend. And it stays stuck as pending forever. The other static files such as CSS seem to load fine though.

Also I can email you temporary ssh access to the droplet I created. I think the other issue I found might actually be related. Because it also only occurs on linux. The other issue revolves around ```.http("localhost:3000").unwrap();```. The ```localhost``` keyword when used returns the generated chrome page "ERR_CONNECTION_REFUSED". There is not even a header response. But I can do the same thing with ```0.0.0.0``` or ```127.0.0.1``` and the page will start to load but gets stuck on the JS files. This might be a different issue and in that case I can open a new issue for that but I think they might be related since the two only occur on linux.

Let me know if there is anything I can help with or clarify.

**Comment by phact** [comment] 2015-08-10 18:32
I an having the exact same issue. Turns out Iron works fine as long as you have fewer than a certain number of files being requested at the same time by your HTML. 

There is no issue on OSX just on linux.

**Comment by phact** [comment] 2015-08-10 18:34
@reem let me know if you need help testing or reproducing this issue. I have an environment set up.

**Comment by phact** [comment] 2015-08-10 19:19
More details, even when I do get it to serve a small app properly (with very few js dependencies), it will only serve to one client. Any other clients that try to make requests after the first has bound hang forever.

**Comment by reem** [comment] 2015-08-12 07:36
Thanks for all the further details, I will investigate this shortly and will post my progress.

**Comment by panicbit** [comment] 2015-08-31 08:10
@AlexanderElias Tha sounds very much like a problem I had, caused by keep-alive connections exhausting the thread-pool. Try increasing the amount of threads to e.g. 100 and see if the problem persists.

**Comment by reem** [comment] 2015-12-29 04:38
Since this is the same issue as documented elsewhere I'm going to close it for organizational purposes.

**Closed by reem** 2015-12-29 04:38 UTC
